### ISSUE TITLE
webssh连接脚本报错问题

### ISSUE THREAD

**Issue by ammengke** [guohongze/adminset#108]
不填写密钥就报403，填写密钥就报下面的问题，不知道咋解决了。。。请大神指导协助解决，感谢！！
jquery.min.js:2 Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
at HTMLInputElement. (http://172.28.200.192/static/webssh/js/jquery.min.js:2:67490)
at Function.each (http://172.28.200.192/static/webssh/js/jquery.min.js:2:2573)
at w.fn.init.each (http://172.28.200.192/static/webssh/js/jquery.min.js:2:1240)
at w.fn.init.val (http://172.28.200.192/static/webssh/js/jquery.min.js:2:67185)
at HTMLDocument. (http://172.28.200.192/webssh/1/:85:24)
at l (http://172.28.200.192/static/webssh/js/jquery.min.js:2:29375)
at c (http://172.28.200.192/static/webssh/js/jquery.min.js:2:29677)

**Comment by guohongze** [comment]
不要填写密钥，想办法解决403权限问题

**Comment by guohongze** [comment]
全新安装，还是老版本升级？

**Comment by ammengke** [comment]
全新安装，更新的最新代码

**Comment by ammengke** [comment]
> 全新安装，还是老版本升级？



> 不要填写密钥，想办法解决403权限问题

403的问题，需要在哪里做什么配置吗？

**Comment by technologynongmin** [comment]
最新版本还是会出现403 webssh forbiden

**Comment by ch-ld** [comment]
403处理办法webssh加上这个   --fbidhttp=False  
不过不安全

**Comment by bavol2000** [comment]
我也出现这个问题，这个应该还是文件权限的问题。单独通过http://localhost:8888来使用密钥登录是没有问题的，而跨域的问题已经有在参数里面添加了--Origin='*',到底要怎么样才能使用密钥来免密登录呢？
