### ISSUE TITLE
auto_install.sh 在执行 django-celery-results-master 报错

### ISSUE THREAD

**Issue by finalkira000** [guohongze/adminset#116]
Installed /usr/lib/python2.7/site-packages/django_celery_results-1.0.4-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 156, in <module>
    include_package_data=False,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

版本信息如下
[root@localhost server]# cat /etc/redhat-release 
**CentOS Linux release 7.2.1511 (Core)** 
[root@localhost server]# 
[root@localhost server]# python
**Python 2.7.5 (default, Apr  9 2019, 14:30:50)** 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> print django.VERSION
**(1, 11, 16, u'final', 0)**

**Comment by Superman-qiang** [comment]
怎么回事，我也是这个错误。

**Comment by guohongze** [comment]
使用干净的minimal版本的操作系统安装一下试试，不要用使用过的系统安装。

**Comment by guohongze** [comment]
setuptools版本的问题更新了。
