### ISSUE TITLE
Python 3下面安装不了

### ISSUE THREAD

**Issue by davideuler** [guohongze/adminset#23]
出错如下： ModuleNotFoundError: No module named 'ConfigParser'
详细错误：
Collecting django==1.9.8 (from -r requirements.txt (line 1))
  Using cached Django-1.9.8-py2.py3-none-any.whl
Collecting sh==1.12.9 (from -r requirements.txt (line 2))
  Using cached sh-1.12.9-py2.py3-none-any.whl
Collecting mysql-python==1.2.5 (from -r requirements.txt (line 3))
  Using cached MySQL-python-1.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fm/hxx1g7yd7dn1m0rtrgfb218w0000gn/T/pip-build-jvoobcwo/mysql-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/var/folders/fm/hxx1g7yd7dn1m0rtrgfb218w0000gn/T/pip-build-jvoobcwo/mysql-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'

**Comment by guohongze** [comment]
我的开发测试环境都是用的python2.7包名为ConfigParser
你的环境是python3, 需要把包名改成configparser
我没有在python3中进行过测试，不保证能够安装，建议把python环境改成2.7，或是新起一个虚拟机。
