### ISSUE TITLE
adminset 客户端执行报错

### ISSUE THREAD

**Issue by qadirluo** [guohongze/adminset#39]
[root@test opt]# python adminset_agent.py 
Get the hardwave infos from host:
Traceback (most recent call last):
  File "adminset_agent.py", line 303, in <module>
    asset_info_post()
  File "adminset_agent.py", line 179, in asset_info_post
    print asset_info()
  File "adminset_agent.py", line 166, in asset_info
    data_info['sn'] = parser_dmi(get_dmi())['Serial Number']
KeyError: 'Serial Number'
[root@jira opt]# vim  adminset_agent.py 
[root@jira opt]# python adminset_agent.py 
Get the hardwave infos from host:
Traceback (most recent call last):
  File "adminset_agent.py", line 303, in <module>
    asset_info_post()
  File "adminset_agent.py", line 179, in asset_info_post
    print asset_info()
  File "adminset_agent.py", line 166, in asset_info
    data_info['sn'] = parser_dmi(get_dmi())['Serial Number']
KeyError: 'Serial Number'

**Comment by guohongze** [comment]
没有获取序列号，你设备是不是少装了什么？或是没有使用install/client/client_install.sh
进行初始化？
