### ISSUE TITLE
访问 montior/system时候是空白的

### ISSUE THREAD

**Issue by PoorWretch** [guohongze/adminset#75]
nginx 有报错 /accounts/permission/user_permission/  500的错误。cmdb模块已经自动注册主机了。

**Comment by PoorWretch** [comment]
[26/Sep/2018 18:46:04] "POST /monitor/system/host/tree/ HTTP/1.0" 200 2
Internal Server Error: /accounts/permission/user_permission/
Traceback (most recent call last):
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/adminset/main/accounts/permission.py", line 127, in get_user_permission
    role_permission = RoleList.objects.get(name=iUser.role)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/adminset/venv/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: RoleList matching query does not exist.
[26/Sep/2018 18:46:04] "GET /accounts/permission/user_permission/ HTTP/1.0" 500 17077

请问需要怎么修复下

**Comment by guohongze** [comment]
用户没有角色列表，你用的什么用户登入的？其它功能有没有问题？
