### ISSUE TITLE
webssh白屏问题

### ISSUE THREAD

**Issue by guohongze** [guohongze/adminset#90]
如果发现此问题，请删除认证信息中的密钥字段。

**Comment by carrison** [comment]
删除认证中的密钥后页面显示：0: error

**Comment by cai823294620** [comment]
@cclauss 最终您是怎么解决的呢？

**Comment by ammengke** [comment]
不填写密钥就报403，填写密钥就报下面的问题，不知道咋解决了。。。
jquery.min.js:2 Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at HTMLInputElement.<anonymous> (http://172.28.200.192/static/webssh/js/jquery.min.js:2:67490)
    at Function.each (http://172.28.200.192/static/webssh/js/jquery.min.js:2:2573)
    at w.fn.init.each (http://172.28.200.192/static/webssh/js/jquery.min.js:2:1240)
    at w.fn.init.val (http://172.28.200.192/static/webssh/js/jquery.min.js:2:67185)
    at HTMLDocument.<anonymous> (http://172.28.200.192/webssh/1/:85:24)
    at l (http://172.28.200.192/static/webssh/js/jquery.min.js:2:29375)
    at c (http://172.28.200.192/static/webssh/js/jquery.min.js:2:29677)

**Comment by technologynongmin** [comment]
> 如果发现此问题，请删除认证信息中的密钥字段。
删除认证中心的密钥字段 ，会出现403

**Comment by jin544642965** [comment]
密码怎么填写啊，一个文本输入框。 wssh是接收的文件型
